### PR TITLE
Feature: Auto Release of JAR

### PR DESCRIPTION
**Pull request by dfuchss**
Added a job that attaches the compiled jar to a new release (part of the release workflow)

### CODE REVIEW

**Review by tsaglam — APPROVED** [review]
Looks good, but is it a draft release by default?
Or do we need to specify `draft: true`?

**Comment by dfuchss** [comment]
> Looks good, but is it a draft release by default? Or do we need to specify `draft: true`?

The Trigger for this workflow is the creation of a release. Therefore, I didn't specified draft mode (as you have created the release before ;) )

**Comment by tsaglam** [comment]
> > Looks good, but is it a draft release by default? Or do we need to specify `draft: true`?
> 
> The Trigger for this workflow is the creation of a release. Therefore, I didn't specified draft mode (as you have created the release before ;) )

Ah, my bad, so I create the release manually, and the JAR will be added automatically, right?

**Comment by dfuchss** [comment]
Yes, you create a release -> the workflow will create the release for Maven Central and add the JAR to the release

**Pull request merged**
