### PR TITLE
Simplified names for map functions in AbstractAntlrListener.java

### PR DESCRIPTION
**Pull request by TwoOfTwelve**
Simplified the names of the mapping functions in AbstractAntlrListener

### CODE REVIEW

**Comment by mbrdl** [comment]
What's the difference between `mapRange` and `mapStart`? Is it simply the token's length? If so, I would suggest removing `mapRange` for clarity, as token length isn't used anywhere and should probably be removed altogether

**Comment by mbrdl** [comment]
And what about `mapTerminal`? I don't really get it

**Comment by Kr0nox** [comment]
Looks good. Only thing missing is what we discussed in #1159

**Comment by tsaglam** [comment]
@TwoOfTwelve should we merge this PR now and address the changes discussed above in another PR? Or do we want to include it here?

**Comment by mbrdl** [comment]
@tsaglam please merge this, I'm starting work on the C++ semantic tokens based on it

**Review by tsaglam — APPROVED** [review]
@TwoOfTwelve Lets move the other issues discussed here into another PR!

**Pull request merged**
