### PR TITLE
Enhance/page cannot be reloaded after refreshing

### PR DESCRIPTION
**Pull request by cyfml**
This PR creates a 404 html, because SPA change pages by JS and it has only one page(index.html). All other urls are not accessed through github-pages, because it doesn't exist. So this 404 page will redirect to public path.

### CODE REVIEW

**Review by sebinside — CHANGES_REQUESTED** [review]
Please use relative redirection as an absolute path will break the dev version of Jplag deployed at https://jplag.github.io/JPlag-Dev/

**Comment by cyfml** [comment]
> Please userelative redirection as an absolute path will break the dev version of Jplag deployed at https://jplag.github.io/JPlag-Dev/

@sebinside I try to redirect to index.html directly, but "index.html" will be in the URL and nothing will be shown.  Let me try to find anthor way.

**Comment by cyfml** [comment]
@sebinside Now, i change it in relative path.

**Comment by sebinside** [comment]
I tested this solution with your deployment at https://cyfml.github.io/JPlag/. While is worked well for reloading on the overview page, it infinitely redirects when reloading a comparison page

**Comment by cyfml** [comment]
> I tested this solution with your deployment at https://cyfml.github.io/JPlag/. While is worked well for reloading on the overview page, it infinitely redirects when reloading a comparison page

I find this problem. Because we have two urls, so i decide to use scripts to generate url dynamiclly. You can test it under https://cyfml.github.io/JPlag/ again.

**Review by sebinside — APPROVED** [review]

**Pull request merged**
