### PR TITLE
Overhauled the end to end tests and added the test code from progpedia

### PR DESCRIPTION
**Pull request by TwoOfTwelve**
Reworked the End-to-End tests. They now use a data set descriptor to identify the sources to be tested.

Also added the progpedia code to the end to end tests.

### CODE REVIEW

**Comment by dfuchss** [comment]
@TwoOfTwelve could you take a look into the failing build :) ?

**Review by tsaglam — COMMENTED** [review]
With my generated expected test values, the E2E tests still fail, but due to:
`Error:    Run 4646: EndToEndSuiteTest.lambda$generateGoldStandardTest$6:214 The gold standard tests are skipped, because no gold standard is defined`

**Review by tsaglam — COMMENTED** [review]
Just a summary of the recent discussions:

- GST changes should be separate PR
- Datsets should be zipped due to bloat
- End-to-end test results should use language regarding plagiarisms and non-plagiarisms and include if the value is higher or lower than expected

**Review by tsaglam — CHANGES_REQUESTED** [review]
A few comments.

**Review by tsaglam — APPROVED** [review]

**Pull request merged**
