### PR TITLE
Fix bugs for WSL

### PR DESCRIPTION
**Pull request by Kr0nox**
When opening the local report viewer on WSL, JPlag terminated since no browser was found. Now there is an info message that the browser could not be opened.
grafik

~~Another issue was that WSL did not access the windows localhost with the given IP Address. Thus, I changed it to the universal Address `0.0.0.0`~~

### CODE REVIEW

**Comment by Kr0nox** [comment]
@TwoOfTwelve @tsaglam Could you quickly verify that the local mode still works on your os

**Comment by tsaglam** [comment]
> Could you quickly verify that the local mode still works on your os

Works for me (macOS Sonoma).

**Review by tsaglam — APPROVED** [review]

**Review by dfuchss — CHANGES_REQUESTED** [review]
Could you test binding to `127.0.0.1` instead of `localhost` or `0.0.0.0` ? Even in the subsystem `python -m http.server -b 127.0.0.1` is accessible for me. So the binding to `0.0.0.0` might not be needed

**Comment by Kr0nox** [comment]
> Could you test binding to 127.0.0.1 instead of localhost or 0.0.0.0 ? Even in the subsystem python -m http.server -b 127.0.0.1 is accessible for me. So the binding to 0.0.0.0 might not be needed

`127.0.0.1` does not work for me

**Comment by dfuchss** [comment]
> > Could you test binding to 127.0.0.1 instead of localhost or 0.0.0.0 ? Even in the subsystem python -m http.server -b 127.0.0.1 is accessible for me. So the binding to 0.0.0.0 might not be needed
> 
> `127.0.0.1` does not work for me

Ok .. I'll test it later :) Still, as default I'd not bind it to 0.0.0.0

**Comment by dfuchss** [comment]
@Kr0nox I've updated the PR. The trick is to ensure that Java understands that the loopback address is IPv4. Please test it on your WSL again :) At my machine that works now :)

**Comment by Kr0nox** [comment]
Yes, works on my system now

**Review by dfuchss — APPROVED** [review]

**Pull request merged**
