### PR TITLE
Language Overview in Readme

### PR DESCRIPTION
**Pull request by JanWittler**
This PR adds an overview of the supported programming languages, meta models, and text (I did not find a proper generic term, thus using language) with their supported versions and the CLI argument name. Additionally, the used parser and the state of the language module are listed.

### CODE REVIEW

**Comment by tsaglam** [comment]
Great idea!

**Comment by JanWittler** [comment]
Seems this suggestion is accepted. I did not find any documentation on the supported C++ and Scheme version (and Python only 3 but not which minor) which is why there is currently a question mark. I have some experience with C++ so might be able to detect the supported version but for Scheme and Python I am completely unexperienced. So help wanted on detecting the correct version for these languages.

**Comment by tsaglam** [comment]
For Python it's something like 3.04 or 3.05, maybe I can find it again.

**Comment by tsaglam** [comment]
A was also thinking of adding a state _label_ for each frontend:

- `established` or `mature` (e.g. Java)
- `beta` (e.g. EMF or C#)
- `legacy` or `outdated` (e.g. C++ or Text)
- `unknown` (Scheme)
 
Not sure what the ideal set of labels is. @jplag/maintainer any ideas?

**Comment by tsaglam** [comment]
Current state: 

| Language | Version | CLI Argument Name | [state](https://github.com/jplag/JPlag/wiki/3.-Language-Modules) | parser
| --- | ---: | --- | :---: | :---: |
| [Java](https://www.java.com) | 17 | java | mature | JavaC |
| [C++](https://isocpp.org) | ? | cpp | legacy | JavaCC |
| [C#](https://docs.microsoft.com/en-us/dotnet/csharp/) | 8 | csharp | beta | ANTLR 4 |
| [Go](https://go.dev) | 1.17 | golang | beta | ANTLR 4 |
| [Kotlin](https://kotlinlang.org) | 1.3 | kotlin | beta | ANTLR 4 |
| [Python](https://www.python.org) | 3.6 | python3 | legacy | ANTLR 4 |
| [R](https://www.r-project.org/) | 3.5.0 | rlang | beta | ANTLR 4 |
| [Scala](https://www.scala-lang.org) | 2.13.8 | scala | beta | Scalameta |
| [Scheme](http://www.scheme-reports.org) | ? | scheme | unknown | JavaCC |
| [EMF Metamodel](https://www.eclipse.org/modeling/emf/) | 2.25.0 | emf-metamodel | alpha | EMF |
| [EMF Metamodel](https://www.eclipse.org/modeling/emf/) (dynamic) | 2.25.0 | emf-metamodel-dynamic | alpha | EMF |
| Text (naive) | - | text | legacy | ANTLR |

**Review by tsaglam — APPROVED** [review]

**Pull request merged**
