### PR TITLE
Fix ComparisonView

### PR DESCRIPTION
**Pull request by nestabentum**
#609

check functionality at https://nestabentum.github.io/JPlag/

### CODE REVIEW

**Comment by tsaglam** [comment]
@nestabentum, sadly, both result zips mentioned [here](https://github.com/jplag/JPlag/issues/609#issuecomment-1226845572) still won't work with the viewer deployed from your fork. I still get a white screen when trying to open the comparison view.
Does it work for you?

**Comment by nestabentum** [comment]
@tsaglam Oh, I see. Unzipping your files shows that there is a problem with the report generation. On which system did you run execute the JPlag run that created these reports?

I suspect that `DirectoryManager#createDirectory` is responsible as it does not yet use File.separator.

**Comment by tsaglam** [comment]
> @tsaglam Oh, I see. Unzipping your files shows that there is a problem with the report generation. On which system did you run execute the JPlag run that created these reports?
> 
> I suspect that `DirectoryManager#createDirectory` is responsible as it does not yet use File.separator.

Windows 10, which would fit as you are probably on macOS where you have proper UNIX file endings. One of the many issues I have with windows! 😄

**Comment by nestabentum** [comment]
I fixed the generation on this branch. You can try generating and displaying the results anew and I'm looking forward to new feedback:)

**Comment by tsaglam** [comment]
> I fixed the generation on this branch. You can try generating and displaying the results anew and I'm looking forward to new feedback:)

Same problem, I click the top most submission pair, but it only shows a white screen and this URL:
`https://nestabentum.github.io/JPlag/comparison/C/A`

Log:
<details><summary>click to show!</summary>

```
GEThttps://nestabentum.github.io/JPlag/
[HTTP/2 200 OK 24ms]

GEThttps://nestabentum.github.io/JPlag/js/chunk-vendors.3c8891ea.js
[HTTP/2 200 OK 26ms]

GEThttps://nestabentum.github.io/JPlag/css/app.967dfcdd.css
[HTTP/2 200 OK 11ms]

GEThttps://nestabentum.github.io/JPlag/js/app.c8482baa.js
[HTTP/2 200 OK 9ms]

Error: Cannot find module '../files/overview.json'
    setup index.js:13
    setup index.js:13
    o runtime-core.esm-bundler.js:155
    Fn runtime-core.esm-bundler.js:7165
    Pn runtime-core.esm-bundler.js:7120
    F runtime-core.esm-bundler.js:5473
    P runtime-core.esm-bundler.js:5448
    E runtime-core.esm-bundler.js:5038
    c runtime-core.esm-bundler.js:5660
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    o runtime-core.esm-bundler.js:155
    L runtime-core.esm-bundler.js:396
    promise callback*R runtime-core.esm-bundler.js:285
    A runtime-core.esm-bundler.js:307
    x runtime-core.esm-bundler.js:313
    X runtime-core.esm-bundler.js:1582
    b runtime-core.esm-bundler.js:1804
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:384
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    set value reactivity.esm-bundler.js:1044
    W vue-router.mjs:3317
    G vue-router.mjs:3190
    promise callback*G vue-router.mjs:3157
    F vue-router.mjs:3082
    install vue-router.mjs:3513
    use runtime-core.esm-bundler.js:4327
    4508 main.ts:8
    Webpack 5
index.js:17:20
GEThttps://nestabentum.github.io/JPlag/img/logo-nobg.fe65cd9a.png
[HTTP/2 200 OK 7ms]

GEThttps://nestabentum.github.io/JPlag/favicon.ico
[HTTP/2 200 OK 7ms]

GEThttps://nestabentum.github.io/JPlag/img/logo-nobg.fe65cd9a.png
GEThttps://nestabentum.github.io/JPlag/img/keyboard_double_arrow_down_black_18dp.1dc03f43.svg
[HTTP/2 200 OK 6ms]

GEThttps://nestabentum.github.io/JPlag/img/help_outline_black_18dp.92160fb9.svg
[HTTP/2 200 OK 6ms]

GEThttps://nestabentum.github.io/JPlag/img/double_arrow_black_18dp.138ba432.svg
[HTTP/2 200 OK 9ms]

TypeError: items is undefined
    filesOfSubmission store.ts:34
    getComparison ComparisonFactory.ts:5
    setup index.js:40
    o runtime-core.esm-bundler.js:155
    Fn runtime-core.esm-bundler.js:7165
    Pn runtime-core.esm-bundler.js:7120
    F runtime-core.esm-bundler.js:5473
    P runtime-core.esm-bundler.js:5448
    E runtime-core.esm-bundler.js:5038
    c runtime-core.esm-bundler.js:5660
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    o runtime-core.esm-bundler.js:155
    L runtime-core.esm-bundler.js:396
    promise callback*R runtime-core.esm-bundler.js:285
    A runtime-core.esm-bundler.js:307
    x runtime-core.esm-bundler.js:313
    X runtime-core.esm-bundler.js:1582
    b runtime-core.esm-bundler.js:1804
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:384
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    set value reactivity.esm-bundler.js:1044
    W vue-router.mjs:3317
    G vue-router.mjs:3190
    promise callback*G vue-router.mjs:3157
    F vue-router.mjs:3082
    a index.js:30
    onClick templateLoader.js:41
    o runtime-core.esm-bundler.js:155
    s runtime-core.esm-bundler.js:164
    n runtime-dom.esm-bundler.js:369
    O runtime-dom.esm-bundler.js:319
    N runtime-dom.esm-bundler.js:337
    M runtime-dom.esm-bundler.js:401
    R runtime-core.esm-bundler.js:5152
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    k runtime-core.esm-bundler.js:5407
    E runtime-core.esm-bundler.js:5031
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    c runtime-core.esm-bundler.js:5587
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    B runtime-core.esm-bundler.js:5708
    F runtime-core.esm-bundler.js:5490
    P runtime-core.esm-bundler.js:5448
    E runtime-core.esm-bundler.js:5038
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
runtime-core.esm-bundler.js:226:16
TypeError: e.isAnonymous is not a function
    _s templateLoader.js:50
    H runtime-core.esm-bundler.js:896
    c runtime-core.esm-bundler.js:5580
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    B runtime-core.esm-bundler.js:5708
    F runtime-core.esm-bundler.js:5490
    P runtime-core.esm-bundler.js:5448
    E runtime-core.esm-bundler.js:5038
    c runtime-core.esm-bundler.js:5660
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    o runtime-core.esm-bundler.js:155
    L runtime-core.esm-bundler.js:396
    promise callback*R runtime-core.esm-bundler.js:285
    A runtime-core.esm-bundler.js:307
    x runtime-core.esm-bundler.js:313
    X runtime-core.esm-bundler.js:1582
    b runtime-core.esm-bundler.js:1804
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:384
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    effect reactivity.esm-bundler.js:1131
    w reactivity.esm-bundler.js:394
    x reactivity.esm-bundler.js:379
    ke reactivity.esm-bundler.js:1008
    set value reactivity.esm-bundler.js:1044
    W vue-router.mjs:3317
    G vue-router.mjs:3190
    promise callback*G vue-router.mjs:3157
    F vue-router.mjs:3082
    a index.js:30
    onClick templateLoader.js:41
    o runtime-core.esm-bundler.js:155
    s runtime-core.esm-bundler.js:164
    n runtime-dom.esm-bundler.js:369
    O runtime-dom.esm-bundler.js:319
    N runtime-dom.esm-bundler.js:337
    M runtime-dom.esm-bundler.js:401
    R runtime-core.esm-bundler.js:5152
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    k runtime-core.esm-bundler.js:5407
    E runtime-core.esm-bundler.js:5031
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    c runtime-core.esm-bundler.js:5587
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5694
    B runtime-core.esm-bundler.js:5708
    F runtime-core.esm-bundler.js:5490
    P runtime-core.esm-bundler.js:5448
    E runtime-core.esm-bundler.js:5038
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
    C runtime-core.esm-bundler.js:5115
    E runtime-core.esm-bundler.js:5035
    I runtime-core.esm-bundler.js:5234
    R runtime-core.esm-bundler.js:5143
runtime-core.esm-bundler.js:226:16
```

</details>

**Comment by nestabentum** [comment]
@tsaglam do your newly generated zips look identical to the previous ones?

**Comment by tsaglam** [comment]
At first glance, it looks fine to me:
[result.zip](https://github.com/jplag/JPlag/files/9425675/result.zip)

**Comment by tsaglam** [comment]
@nestabentum re-zipping helps! I can get both zips to work correctly by unzipping them with 7zip and rezipping the contents. This means the way JPlag zips the files might be an issue, right?

**Comment by nestabentum** [comment]
The problem that remained was that the report viewer could only process unix like paths correctly. Windows paths are now converted to the unix style for internal use with the helpt of library [slash ](https://www.npmjs.com/package/slash).
The issue is now fixed and this PR is good to go @dfuchss.

**Comment by dfuchss** [comment]
@nestabentum if it's ready to review , please click on ready for review :)

**Review by robinmaisch — APPROVED** [review]
Nice! Nothing in particular to critizise about these changes from my end.
Fiddling around with the UI a bit, I thought it would be nice if the UI text was not selectable (`user-select: none;`). Code clearly should stay selectable.
But that is a different concern than this PR. If you need to submit changes anyway, you can keep that in mind if you like the idea.

**Review by dfuchss — APPROVED** [review]

**Pull request merged**
