### PR TITLE
Feature/antlr language utils

### PR DESCRIPTION
**Pull request by TwoOfTwelve**
Adds a new maven module, containing a common parser implementation for all antlr languages.
Part of #983

### CODE REVIEW

**Comment by tsaglam** [comment]
@TwoOfTwelve, you need to adapt the coverage pom in order for us to see the coverage correctly:
https://github.com/jplag/JPlag/blob/3986f58f2f355f00cac3e87a6e16f82183ad530b/coverage-report/pom.xml

**Review by tsaglam — APPROVED** [review]
Looks good. Maybe we can see with the typescript module how intuitive the system is (@Kr0nox just FYI) and then tweak it if required.

**Comment by Kr0nox** [comment]
@TwoOfTwelve Is there a way two tokens for the same RuleContext get added in the desired order?
```
this.createRangeMapping(FunctionDeclarationContext.class, ASSIGNMENT);
this.createStartStopMapping(FunctionDeclarationContext.class, METHOD_BEGIN, METHOD_END);
```
In this case `ASSIGNMENT` always gets added after `Method_BEGIN`. This is also the case if these two calls are swapped

**Comment by Kr0nox** [comment]
Yes that solves the issue 👍

**Pull request merged**
