### PR TITLE
Java API for JPlag

### PR DESCRIPTION
**Pull request by krusche**
In this pull request, @philippbauch has implemented a Java API for JPlag that allow other tools (e.g. [Artemis](http://github.com/ls1intum/Artemis)) to invoke JPlag in a more object oriented way instead of using command line options.

We also added new objects (shown in the README file in a UML class diagram) to improve the result reporting so that other tools can interpret the results more easily.

#### Example 

```java
JPlagOptions options = new JPlagOptions("/path/to/rootDir", LanguageOption.JAVA_1_9);
options.setBaseCodeSubmissionName("template");

JPlag jplag = new JPlag(options);
JPlagResult result = jplag.run();

List<JPlagComparison> comparisons = result.getComparisons();

// Optional
File outputDir = new File("/path/to/output");
Report report = new Report(outputDir);

report.writeResult(result);
```

#### Class Diagram

This PR also updates the JPlag version to 3.0.0, but tries to stay compatible with 2.x versions and previous workflows.

We are happy to discuss any changes or improvements.

Please note: Some folders have been deleted to simplify the project structure, but we can also add them again in case they are still needed

### CODE REVIEW

**Review by tsaglam — COMMENTED** [review]
Thanks for the comprehensive contribution! I reviewed the changes and they look great. When @sebinside had a chance to look at them as well we will merge them.

**Comment by dfuchss** [comment]
@krusche @philippbauch is the version of the PR the version of JPlag you are currently using for Artemis ?

**Comment by krusche** [comment]
> @krusche @philippbauch is the version of the PR the version of JPlag you are currently using for Artemis ?

yes, except some smaller changes done by @philippbauch in the meantime and some smaller changes done by @tsaglam and @sebinside 

As soon as this PR is merged, it would be awesome if the JPlag library can be published to Maven Central (we have done this before and can help with it), then we could integrate the dependency more easily into Artemis.

**Comment by dfuchss** [comment]
Ok. Thanks for the information:
Then we should address two points (in this or a follow-up PR):

1. The order of the similarities is broken (the image is from a JPlag Run in Artemis 4.12.2)
<details>

image

</details>
2. The details web view hasn't two scroll bars as usual to scroll each submissions independent:
<details>

image

</details>

**Review by sebinside — COMMENTED** [review]
There are several bugs remaining in the CLI, but these can be fixed afterward.

**Pull request merged**
