### PR TITLE
Introduce a cleaner way to use suppress warnings

### PR DESCRIPTION
**Pull request by dfuchss**
As mentioned by @JanWittler in #514 , we should document our suppress warning better :)

Here's a simple proposal for that

### CODE REVIEW

**Comment by dfuchss** [comment]
Ok Sonarlint ignores it. Locally it works :(

**Comment by dfuchss** [comment]
I think we have to investigate more here.

**Comment by tsaglam** [comment]
As an alternative, we can just merge #555.

**Comment by JanWittler** [comment]
> As an alternative, we can just merge #555.

If that solves all suppressed warnings, I would definitely go with that solution and thus close this PR. (But thanks for the effort to solve my complaints :D )

**Pull request closed without merging**
