### PR TITLE
Remove unnecessary submission length check in GreedyStringTiling

### PR DESCRIPTION
**Pull request by uuqjz**
This PR addresses the issue #1211

### CODE REVIEW

**Comment by tsaglam** [comment]
You have to clean up the commit history of this PR. For small PRs like this, I advocate for creating a new branch based on the (origin) develop branch. If you want these changes in your own feature branches, you can always merge develop into your own feature branches.

**Comment by uuqjz** [comment]
> For small PRs like this, I advocate for creating a new branch based on the (origin) develop branch.

I will do so for future PRs

I don't know how to clean the commit history of this PR.
It effectively removes 8 lines and the commit history will be squashed into one merge-commit.
If you think it is necessary I can close the PR, branch (origin) develop and make a new PR.

**Comment by tsaglam** [comment]
It is necessary, PRs should always only contain the commits relevant to the PR. For now, just try to update your PR branch from the develop branch.

**Comment by uuqjz** [comment]
Will open a clean PR later

**Pull request closed without merging**
