### PR TITLE
Add R language frontend

### PR DESCRIPTION
**Pull request by robinmaisch**
Let's add R to JPlag! The R branch should be perfectly runnable.
If there is any trouble or suggestions, let me know.

Adressing Issues #75 #345

### CODE REVIEW

**Comment by tsaglam** [comment]
Currently, this PR contains multiple newly added frontends. I would suggest one frontend per PR. This would include a short readme in the frontend and some test cases. Any other changes should be explained and well-argued for in the PR description. E.g. changes to the token printer. For the PR description, try to point out what you changed/added and why. Smaller bug fixes, like the fix in the ErrorConsumer, should be another small PR.

**Comment by robinmaisch** [comment]
Got it, I'll work on these points right away.

**Comment by robinmaisch** [comment]
@tsaglam In a new frontend, are the tests supposed to be disabled, like the tests in MinimalCSharpFrontendTest?

**Comment by tsaglam** [comment]
No, they should be enabled. When you design meaningful tests (as we discussed recently), they should be enabled by default.

**Pull request closed without merging**
