### PR TITLE
Enhance/codes selection

### PR DESCRIPTION
**Pull request by cyfml**
This PR is based on last PR. It enables that codes can be selected and copied. And mouse icon is changed to grab-hand, when mouse is hover on file header.

### CODE REVIEW

**Review by sebinside — APPROVED** [review]

**Comment by sebinside** [comment]
@cyfml This is also fine. Please clean the history so that we can also merge this PR.

**Comment by cyfml** [comment]
@sebinside I have cleaned the history, but PR has a problem. Can you take a look?

**Comment by tsaglam** [comment]
> @sebinside I have cleaned the history, but PR has a problem. Can you take a look?

Did you merge the develop branch into your PR branch?

**Comment by cyfml** [comment]
> > @sebinside I have cleaned the history, but PR has a problem. Can you take a look?
> 
> Did you merge the develop branch into your PR branch?

Yes. Merged.

**Comment by cyfml** [comment]
You can check the last commit.

**Comment by sebinside** [comment]
@cyfml What do you mean with `PR has a problem`?

**Comment by cyfml** [comment]
@sebinside  It seems build failed in Actions.

Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project aggregator: Parameter 'sonar.pullrequest.key' is mandatory for a pull request analysis -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Pull request merged**
