### PR TITLE
Some small e2e tests for report viewer

### PR DESCRIPTION
**Pull request by Kr0nox**
This PR adds some small tests for the basic functionality of each page

### CODE REVIEW

**Comment by Kr0nox** [comment]
@sebinside This PR is now ready for review.
Snapshots are added for windows and linux systems (although font faces and other criteria can be different).
The html report gets automatically added to the artifacts of the action run

**Comment by Kr0nox** [comment]
The tests will need to be changed either in this PR after merging #1323 or in the other PR after merging this one.

**Review by sebinside — COMMENTED** [review]
At least for me, the tests fail locally with 

```    
Test timeout of 30000ms exceeded.
Error: page.waitForEvent: Page closed
waiting for event "filechooser"
```

but that could also be a configuration thing, playwright is not exactly lightweight :)

Other than this we should discuss which standards we want regarding code quality and comprehensiveness of these test cases in the next meeting. I see the benefit of direct feedback by the CI/CD pipeline if we break something. However, this can quickly develop into something hard to maintain and hard to keep up-to-date.

**Comment by Kr0nox** [comment]
Before merging this, develop should be merged into this branch again, even if there are no merge conflicts, to ensure the tests are all still correct

**Review by sebinside — APPROVED** [review]
Good simplification, it now even works locally for me :)

**Comment by Kr0nox** [comment]
@sebinside Merged and updated the test that were failing. Can be merged from my side

**Pull request merged**
